[package]
name = "lankm-headless"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }

[target.'cfg(windows)'.dependencies.windows]
version = "^0.58.0"
features = [
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging"
]
