[package]
name = "lankm"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "^1.4"

[dependencies.windows]
version = "0.58.0"
features = [
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging"
]
